name: ibankit_dart
description: Translate to dart from https://github.com/koblas/ibankit-js
version: 1.0.0
repository: https://github.com/DanWlker/ibankit_dart.git

environment:
  sdk: ">=2.17.5 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
